name: Deploy to GitHub Pages

on:
  push:
    branches:
      - feature/versionnumber

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: application

      - name: print filesystem
        run: ls

      - name: Change into application directory
        run: cd application

      - name: print filesystem
          run: ls

      - name: Install dependencies
        run: npm install

      - name: Run deploy script
        run: npm run deploy
